### ISSUE TITLE
Tag suggestion for Docker Hub project

### ISSUE THREAD

**Issue by herokang** [snowdream/dockerfiles#10]
Hi, 
I am Kang Yin, a graduate student of Institute of Software, Chinese Academy of Sciences. Now we are doing a research on how to recommend tags for Docker Hub’s projects. We applied text mining and natural language processing to build a tag recommendation system for Docker projects.
We notice that you have created repositories on Docker Hub, which are named _snowdream/android-ndk_  and _snowdream/desktop_ , and the projects address are [https://hub.docker.com/r/snowdream/android-ndk/](https://hub.docker.com/r/snowdream/android-ndk/) , [https://hub.docker.com/r/snowdream/desktop/](https://hub.docker.com/r/snowdream/desktop/) 
Since the developers knows their projects better, we want to evaluate our recommendation results with your help as the project developer. We want to know if the recommended tags are reasonable for your projects. 
The following tags (ranked by order) are generated from our model automatically. Would you like to do me a favor and reply with what tags are reasonable (Good) and what are not (Bad), in form of, “Good tags: ***, ***; Bad tags: ***, ***”.

The recommend tags for your project _snowdream/android-ndk_ are listed as follows:

> `android, android-ndk, android-25, android projects, android support libraries, gradle, snowdream, openjdk, google-play, google play services`

The recommend tags for your project _snowdream/desktop_ are listed as follows:

> `desktop, mate-desktop, mate, snowdream, client, session, x2go client, ssh, debian, server`

It will be a great help if you can give us a feedback. 
Thank you so much for your precious time.

**Comment by snowdream** [comment]
@herokang thank you .
