### ISSUE TITLE
The android command is no longer available.

### ISSUE THREAD

**Issue by snowdream** [snowdream/dockerfiles#3]
bogon:~ snowdream$ android update sdk --filter tools --no-ui
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager

**Comment by Jonothan-Ho** [comment]
How to solve the problem?

**Comment by snowdream** [comment]
@Jonothan-Ho
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager

like: https://github.com/snowdream/dockerfiles/blob/master/android/sdk/Dockerfile
