### ISSUE TITLE
X2Go Client could not start X11 server.

### ISSUE THREAD

**Issue by snowdream** [snowdream/dockerfiles#6]
X2Go Client requires XQuartz to be installed. 

If XQuartz is already installed on your system, 
please select the correct path in the now upcoming dialog. 
Refer to the end of this message for path examples, 
in case you do not know the exact location yourself. 

Should you have not installed XQuartz yet, please 
follow the outlined steps: 

MacPorts users, please install either the port xorg-server 
or the port xorg-server-devel. 
Upon successful installation, please follow the instructions printed 
by the port utility to autostart/load the server. 

All other users, please obtain and install XQuartz from: 

https://xquartz.macosforge.org/

Afterwards, restart X2Go Client and select the correct path 
to the X11 application in the general X2Go Client settings. 
This will most likely be 

/Applications/MacPorts/X11.app

or 

/Applications/Utilities/XQuartz.app

**Comment by mutech** [comment]
I have the same problem. XQuartz is installed, x2go client finds it in /Application/Utilities and recognizes its version. XQuartz is running with an active client (term). It also does not work if XQuartz is not running. A fresh install of XQuartz does not help either.

The connection to the host box is working (at least x2go is connecting)

**Comment by MerPozoBuil** [comment]
Hi mutech and snowdream, 

I have the exact problem right now. Did you figure it out how to solve this?

Thanks in advance

**Comment by mutech** [comment]
@mmpb19, no sorry, I gave up on it.

**Comment by MerPozoBuil** [comment]
mutech, thanks for the reply!

**Comment by MerPozoBuil** [comment]
Hi Mutech, 

at the end I figure it out how to make it work. The x2go only works with the Xqarts version 2.7.7: XQuartz-2.7.7.dmg, in case you want to try again! :)

Cheers!

**Comment by buncismamen** [comment]
I use XQuartz 2.7.11  the problem persist

**Comment by JimmyCushnie** [comment]
Sad to report that this doesn't seem to be working anymore. MacOS Sonoma 14.5, I get the issue described in the OP using both XQuartz 2.8.5 and 2.7.7.
