### ISSUE TITLE
java image from hub.docker.com  is deprecated. Any plans in switching to openjdk image? 

### ISSUE THREAD

**Issue by bogdanRada** [snowdream/dockerfiles#9]
Hello, 
   According to this https://hub.docker.com/_/java/ , the java image is deprecated. Are there any plans on switching to the new base image for java? Thank you very much. 
   This would help me a lot, because i use this repository very often. Problem found when trying to install virtualbox inside a docker container  having "snowdream/gradle:3.3" as a base image...found that the kernel is a year old and virtualbox is not happy about it :(  Any help would be greatly appreciated.

**Comment by snowdream** [comment]
use "snowdream/gradle:4.3" instead, it has use openjdk.
